name: yapm
version: git
summary: Yet Another Package Manager
description: |
  Yet Another Package Manager
base: core18
confinement: devmode


parts:
  yamp:
    plugin: python
    python-version: python3
    source: .

apps:
  yamp:
    command: yamp.py